server:
  port: 8080

logging:
  level:
    root: DEBUG

application:
  security:
    jwt-token-secret: themostsecuresecret
    jwt-issuer: buythebookstore
    jwt-token-expiry: 1800000

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: userdb
      port: '27017'
      host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
  instance:
    prefer-ip-address: false

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    stock-service:
      serviceId: stock-service
      path: /stock/**
    recommendation-service:
      serviceId: recommendation-service
      path: /recommendation/**
    tracker-service:
      serviceId: tracker-service
      path: /tracker/**
  ribbon:
    eager-load:
      enabled: 'true'
  host:
    connect-timeout-millis: '50000'
    socket-timeout-millis: '50000'
  ribbon-isolation-strategy: THREAD

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000